git blame ignore instructions added
angr/angr-doc pull request #448
Opened 2023-01-17 23:50 UTC by zwimer

`git blame` currently reflects users who made large reformatting of code to `angr` in `git blame` instead of the original authors, this PR should address that.

2023-01-18 00:17 UTC, twizmwazin requested changes
Can we just link to https://docs.github.com/en/repositories/working-with-files/using-files/viewing-a-file#ignore-commits-in-the-blame-view instead of re-writing this?

2023-01-18 22:02 UTC, zwimer commented
I'd prefer the description but I have no issues with the later; feel free to change it.

2023-01-18 22:05 UTC, zwimer commented
The CI is actually passing, the failure rating is because the pre-commit CI was not yet setup correctly when this ran.

2023-04-04 01:01 UTC, twizmwazin commented
Closing as these docs are no longer used

2023-04-04 01:01 UTC, closed without merging